### ISSUE TITLE
Some questions about the dependencies to run this project

### ISSUE THREAD

**Issue by nowhereman1999** [RemonComputer/Robotic-Nano-Degree-Project-5#1]
Hi,I want to run your project on noetic in Ubuntu 20.04 but there are some dependencies error when I try to install the required packges as below：
![image](https://user-images.githubusercontent.com/53631206/215302647-c3b4fe7e-b917-4094-b556-db3705a5884e.png)
I searched the turtlebot_teleop package and found it was only surpported up to melodic,so is there a possibility to run on noetic or I have  to reinstall the ros distro to fit the package？I‘d appreciated if you can give me some advice!:-)

**Comment by RemonComputer** [comment]
I think you might get away without installing the turtle bot packages, I don't use the turtle bot Robot in my project, can you try to run the project without those packages and let me know if there are any issues?

**Comment by nowhereman1999** [comment]
> I think you might get away without installing the turtle bot packages, I don't use the turtle bot Robot in my project, can you try to run the project without those packages and let me know if there are any issues?

OK,I'll try it later and give you feedback if there is any problem:-)

**Comment by nowhereman1999** [comment]
@RemonComputer Hi, unfortunately the catkin_make failed and threw such a error shown in the screenshot below：
![image](https://user-images.githubusercontent.com/53631206/215373910-2613a16c-5e80-49d5-88f6-0d3d1e1b6fb1.png)
I‘ve follwed your advice and skip the section to install the turtlebot related packages：
![image](https://user-images.githubusercontent.com/53631206/215374265-53446af5-0365-449f-9edc-b4db04af3531.png)
However,I think the error is due to the turtlebot_teleop package is not installed,so is this means I still need to install the turtlebot packages or something else?

**Comment by RemonComputer** [comment]
I removed turtlebot repos from the ROS Workspace
```
sudo rm -r turtlebot turtlebot_interactions/ turtlebot_simulator/
```
and I was able to compile the code without any problems, from the screenshot you are trying to compile turtlebot_teleop, please remove all turtlebot repos from your ROS workspace, and try recompiling the project

**Comment by nowhereman1999** [comment]
> I removed turtlebot repos from the ROS Workspace
> 
> ```
> sudo rm -r turtlebot turtlebot_interactions/ turtlebot_simulator/
> ```
> 
> and I was able to compile the code without any problems, from the screenshot you are trying to compile turtlebot_teleop, please remove all turtlebot repos from your ROS workspace, and try recompiling the project

Hi,I've removed all the turtlebot repos from the ROS Workspace and I have successfully complied the project but the rviz and gazebo seems have no response at all:
![image](https://user-images.githubusercontent.com/53631206/215652364-b355377a-b393-4642-85ad-18e9a1e51db8.png)
![image](https://user-images.githubusercontent.com/53631206/215652403-d391dd56-3524-46d1-916c-de07e2fe7dc7.png)
they just stay in this state and the xterm terminal throw a error like this：
![image](https://user-images.githubusercontent.com/53631206/215652679-eae6d35d-dfa9-4a00-b4fa-9a5f425a1217.png)
I try to control the robot to walk around as you mentioned in README,but the robot has no change when I press the arrow key，so is this normal or there a step I did wrong again?

**Comment by nowhereman1999** [comment]
> > I removed turtlebot repos from the ROS Workspace
> > ```
> > sudo rm -r turtlebot turtlebot_interactions/ turtlebot_simulator/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and I was able to compile the code without any problems, from the screenshot you are trying to compile turtlebot_teleop, please remove all turtlebot repos from your ROS workspace, and try recompiling the project
> 
> Hi,I've removed all the turtlebot repos from the ROS Workspace and I have successfully complied the project but the rviz and gazebo seems have no response at all: ![image](https://user-images.githubusercontent.com/53631206/215652364-b355377a-b393-4642-85ad-18e9a1e51db8.png) ![image](https://user-images.githubusercontent.com/53631206/215652403-d391dd56-3524-46d1-916c-de07e2fe7dc7.png) they just stay in this state and the xterm terminal throw a error like this： ![image](https://user-images.githubusercontent.com/53631206/215652679-eae6d35d-dfa9-4a00-b4fa-9a5f425a1217.png) I try to control the robot to walk around as you mentioned in README,but the robot has no change when I press the arrow key，so is this normal or there a step I did wrong again?

By the way,I also want to ask you that why you use xterm to launch the ros node in the test_slam.sh instead of just use the default terminal comes with ubutntu:
![image](https://user-images.githubusercontent.com/53631206/215654851-f0ab5763-9c94-4b74-b7d8-d9020e77574d.png)
is this because you run this project in a virtual machine instead of a physical machine？

**Comment by RemonComputer** [comment]
- There was an issue that a mesh path was hardcoded in the world file, I fixed this issue.
- I replaced the scripts with ros launch files for convenience.
- I modified some path planning parameters.
- Please note that sometimes the robot gets trapped in some locations due to the path planning parameters, I am no expert in the path planning parameters (move_base configuration files in the config folder), but I tried my best.
- I added those modifications in the ``fix/remon/remove_turtlebot`` branch, please use this branch.
- I modified the README to use the launch files.
- Please try the code again and let me know if it is working.
- I was using xterm because this was used in the Udacity Template Project, but I think ros launch files is better

**Comment by nowhereman1999** [comment]
> * There was an issue that a mesh path was hardcoded in the world file, I fixed this issue.
> * I replaced the scripts with ros launch files for convenience.
> * I modified some path planning parameters.
> * Please note that sometimes the robot gets trapped in some locations due to the path planning parameters, I am no expert in the path planning parameters (move_base configuration files in the config folder), but I tried my best.
> * I added those modifications in the `fix/remon/remove_turtlebot` branch, please use this branch.
> * I modified the README to use the launch files.
> * Please try the code again and let me know if it is working.
> * I was using xterm because this was used in the Udacity Template Project, but I think ros launch files is better

OK,thanks for your detailed reply,I will try the new branch you mentioned and give you feedback as soon as possible!:-)

**Comment by nowhereman1999** [comment]
> * fix/remon/remove_turtlebot

Sorry to response you so lately because I'm working on another project these days util today I have the chance to test your updated code,However,it is my pleasure to announce you that I have successfully run the simulations following your advice：
![image](https://user-images.githubusercontent.com/53631206/216868396-caa2a465-af14-4328-ad04-dc626e4c16ff.png)
![image](https://user-images.githubusercontent.com/53631206/216868417-40ec960d-5940-40e0-8681-d68d8b7db3b7.png)
As you can see,I can control the robot with my keyboard and I guess other part should be fine,but there is still a little question about the compilation process,is it possible to use `catkin build` to build the whole project?and if it means I only need to replace the `catkin_make`  with `catkin build`  in the Building the project part of README?I prefer to use catkin tools to configure my project now which is more flexiable and friendly to the packages in the workspace,hope you can give me more advice!:-)

**Comment by nowhereman1999** [comment]
@RemonComputer I'm sorry to ask you again when you haven't replied to me,but there seems to be an error when I try to test the navigation and the home robot service delivery：
![image](https://user-images.githubusercontent.com/53631206/216875048-2e70f038-88b7-4a36-b5ec-905f547f938a.png)
as you can see,the map I saved through slam does not overlap with the grid map and there is no response at all of the robot after I use the 2DNav goal button and point to a goal,so what causes this situation,is there any step I did wrong again but I just follow the README you have updated in the `fix/remon/remove_turtlebot` branch,looking forward to your reply!:-)

**Comment by RemonComputer** [comment]
Hello @Hezhexi2002 

Sorry for my late reply, I was a bit busy at work,

Regarding `catkin build`I am not familiar with it, if it is used to configure the build and build the project, then I think you should be able to replace `catkin_make` but I am not familiar with it.

**Comment by RemonComputer** [comment]
@Hezhexi2002 
Regarding your second enquiry, I don't think your map should be aligned with the grid map, and I don't believe this is a problem.

- You need to click the 2D Nav Goal Button and then click on a position inside the map and drag, you will see a big green arrow which will point in the direction of the final pose of the Robot.
- Sometimes due to the parameters of the path planner, it cannot plan a path to some position.
- To test if this is the problem or not, try to set a position in front of the robot, to make the robot walk in a straight line, if the robot can reach this position, then it might be the problem mentioned in the previous point else if the robot still cannot walk in a straight line, then there are other problems that we need to investigate.

**Comment by nowhereman1999** [comment]
@RemonComputer OK,thanks for your detailed reply but the robot still has no response even after I set a position in front of the robot in rviz:
![image](https://user-images.githubusercontent.com/53631206/217759432-e12544e8-30ef-4c4b-984b-1070d641c13c.png)
and the question I mentioned last time that the map does not overlap with the grid map seems to be solved after I change the type of Fixed Frame from odom to map as shown in the picture above.Besides,I notice that there are some erros after I run the `roslaunch my_robot test_navigation.launch`：
![image](https://user-images.githubusercontent.com/53631206/217764373-3bc21e55-cbb9-40bd-9845-437e33190341.png)
it seems that the move_base didn't work,so is this the reason causes the problem above?I'd appreciated it if you could give me more advice!:-)

**Comment by RemonComputer** [comment]
It seems that you need to install the amcl and move_base nodes,
can you run the following commands and try running the project again,
```
# Install rosdep
sudo apt-get install python3-rosdep
# intailize ros dep
sudo rosdep init
# update rosdep
rosdep update
# Install the missing packages
rosdep install -i move_base amcl --rosdistro=noetic
```

**Comment by nowhereman1999** [comment]
> It seems that you need to install the amcl and move_base nodes, can you run the following commands and try running the project again,
> 
> ```
> # Install rosdep
> sudo apt-get install python3-rosdep
> # intailize ros dep
> sudo rosdep init
> # update rosdep
> rosdep update
> # Install the missing packages
> rosdep install -i move_base amcl --rosdistro=noetic
> ```

@RemonComputer Hi,I'm very excited to tell you that it works now after I install the navigation package through `sudo apt-get install ros-noetic-navigation`

https://user-images.githubusercontent.com/53631206/217993299-478eb273-e11b-44db-9919-d8bd67124046.mp4

and there is also no problem with the home robot service delivery which I have tested.Anyway,I'll dig deeper into your project afterwards and try to integrate your algorithm into my project,thanks you again for your patience in the past two days.Hope your work is progressing well too!

Best regards!

**Comment by RemonComputer** [comment]
Thank you @Hezhexi2002,
and Thanks for highlighting some problems in my project. It was a pleasure serving your request
